ARG ALPINE_VERSION=3.20
ARG YQ_VERSION=v4.45.1
ARG BATS_VERSION=v1.11.1

FROM --platform=amd64 alpine:${ALPINE_VERSION}

ARG YQ_VERSION
ARG BATS_VERSION

RUN apk add --no-cache bash jq curl ca-certificates gettext && \
	mkdir -p /opt/resource

WORKDIR /opt/resource

COPY ./concourse/resource-type/scripts/check.sh /opt/resource/check
COPY ./concourse/resource-type/scripts/in.sh /opt/resource/in
COPY ./concourse/resource-type/scripts/out.sh /opt/resource/out
COPY ./bin/send-to-slack.sh /opt/resource/send-to-slack
COPY ./lib/ /opt/resource/lib/
COPY ./VERSION /opt/resource/VERSION

# Install test dependencies
RUN chmod +x /opt/resource/check /opt/resource/in /opt/resource/out /opt/resource/send-to-slack && \
	find /opt/resource/lib -type f -name '*.sh' -exec chmod +x {} + && \
	apk add --no-cache make git shellcheck shfmt coreutils wget && \
	git config --global --add safe.directory /workspace && \
	wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" && \
	chmod 755 /usr/local/bin/yq && \
	(git clone --depth 1 --branch "${BATS_VERSION}" https://github.com/bats-core/bats-core.git /tmp/bats-core && \
	/tmp/bats-core/install.sh /usr/local && \
	rm -rf /tmp/bats-core) && \
	apk del wget && \
	rm -rf /var/cache/apk/*

ENTRYPOINT ["/bin/bash"]
