FROM --platform=amd64 alpine:3.20

RUN apk add --no-cache bash jq curl ca-certificates gettext && \
	mkdir -p /opt/resource

WORKDIR /opt/resource

COPY ./concourse/resource-type/scripts/check.sh /opt/resource/check
COPY ./concourse/resource-type/scripts/in.sh /opt/resource/in
COPY ./concourse/resource-type/scripts/out.sh /opt/resource/out
COPY ./bin/send-to-slack.sh /opt/resource/send-to-slack
COPY ./lib/ /opt/resource/lib/
COPY ./VERSION /opt/resource/VERSION


# Install test dependencies
RUN apk add --no-cache make git shellcheck shfmt coreutils wget && \
	git config --global --add safe.directory /workspace && \
	wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && \
	chmod 755 /usr/local/bin/yq && \
	(git clone --depth 1 https://github.com/bats-core/bats-core.git /tmp/bats-core && \
	/tmp/bats-core/install.sh /usr/local && \
	rm -rf /tmp/bats-core) && \
	apk del wget && \
	rm -rf /var/cache/apk/*

ENTRYPOINT ["/bin/bash"]


