---
# Example Concourse CI pipeline for block-level from_file
# Uses external JSON fixtures from the repository and output/example.txt

resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: ((TAG))

resources:
  - name: send-to-slack
    type: git
    source:
      uri: https://github.com/sunflowersoftware/send-to-slack.git
      branch: main

  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: ((channel))

jobs:
  - name: blocks-from-file-3
    public: true
    plan:
      - get: send-to-slack
      - task: prepare-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set -eo pipefail
                mkdir -p output
                echo "Example file for blocks-from-file-3" > output/example.txt
          outputs:
            - name: output

      - put: slack-notification
        params:
          <<: *common_slack_params
          blocks:
            - from_file: send-to-slack/examples/fixtures/blocks-from-file-3.json

  - name: concourse-metadata
    public: true
    plan:
      - get: send-to-slack
      - put: slack-notification
        params:
          <<: *common_slack_params
          blocks:
            - from_file: send-to-slack/examples/fixtures/blocks-concourse-metadata.json
