resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: ((TAG))

resources:
  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: ((channel))

jobs:
  - name: context-with-image-and-text-elements
    plan:
      - put: slack-notification
        
        params:
          <<: *common_slack_params
          text: "Testing context block with image element and mrkdwn text element"
          blocks:
            - context:
                elements:
                  - type: image
                    image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                    alt_text: "Sunflower"
                  - type: mrkdwn
                    text: "Location: **Dogpatch**"

  - name: context-with-multiple-text-elements-and-block-id
    plan:
      - put: slack-notification
        
        params:
          <<: *common_slack_params
          text: "Testing context block with multiple text elements (plain_text and mrkdwn) and block_id"
          blocks:
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Deployment completed successfully*"
            - context:
                elements:
                  - type: plain_text
                    text: "Environment: production"
                  - type: mrkdwn
                    text: "*Version:* v1.2.3"
                  - type: plain_text
                    text: "Status: Success"
                  - type: mrkdwn
                    text: "*Build:* #1234"
                block_id: "deployment_context_001"
