resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: ((TAG))

resources:
  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: ((channel))

jobs:
  - name: divider-basic-separator
    plan:
      - put: slack-notification
        
        params:
          <<: *common_slack_params
          text: "Testing divider block as basic content separator"
          blocks:
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Content above the divider"
            - divider: {}
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Content below the divider"

  - name: divider-with-block-id-separating-sections
    plan:
      - put: slack-notification
        
        params:
          <<: *common_slack_params
          text: "Testing divider block with block_id separating multiple sections"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Report Sections"
            - divider:
                block_id: "header_section_divider"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Summary*\nFirst section content"
            - divider:
                block_id: "summary_details_divider"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Details*\nSecond section content"
            - divider:
                block_id: "details_footer_divider"
            - context:
                elements:
                  - type: plain_text
                    text: "Report footer information"
