resource_types:
  - name: slack
    type: docker-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  - name: basic-divider
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - divider: {}

  - name: divider-with-block-id
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - divider:
                block_id: "section_separator"

  - name: divider-with-sections
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Report sections"
          blocks:
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Summary*"
            - divider: {}
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Details*"
            - divider: {}
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Conclusion*"

  - name: divider-multiple
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Multiple sections example"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Report"
            - divider:
                block_id: "header_separator"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Section 1"
            - divider:
                block_id: "first_section_separator"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Section 2"
            - divider:
                block_id: "second_section_separator"
            - context:
                elements:
                  - type: plain_text
                    text: "Auto-generated report"

  - name: divider-in-context
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Divider example"
          blocks:
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Content before divider"
            - divider: {}
            - context:
                elements:
                  - type: plain_text
                    text: "Context after divider"
                  - type: mrkdwn
                    text: "*Time:* $(date)"
