---
# Example Concourse CI pipeline for Slack file blocks
# File blocks upload files and create image blocks for images, rich_text blocks for other files

resource_types:
  - name: slack
    type: docker-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  # Single file block
  - name: file-block-basic
    public: true
    plan:
      - task: create-report
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                echo "Build completed at $(date)" > output/build-report.txt
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - file:
                path: output/build-report.txt
                title: "Build Report"

  # Multiple file blocks
  - name: file-blocks-multiple
    public: true
    plan:
      - task: create-multiple-files
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                echo "Q1 Sales Data" > output/q1-sales.csv
                echo "Q2 Sales Data" > output/q2-sales.csv
                echo "Summary Report" > output/summary.txt
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Monthly sales reports"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Sales Reports"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Sales reports attached:"
            - divider: {}
            - file:
                path: output/q1-sales.csv
                title: "Q1 Sales Data"
            - file:
                path: output/q2-sales.csv
                title: "Q2 Sales Data"
            - file:
                path: output/summary.txt
                title: "Summary Report"
            - context:
                elements:
                  - type: plain_text
                    text: "Generated by CI/CD Pipeline"

  # File block with variable interpolation
  - name: file-block-with-interpolation
    public: true
    plan:
      - task: create-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                cat > output/config.json <<EOF
                {
                  "version": "1.2.3",
                  "environment": "production",
                  "features": ["feature1", "feature2"]
                }
                EOF
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - file:
                path: output/config.json
                title: "Configuration File"
                interpolate_file_contents_to_var: "CONFIG_DATA"

      - task: use-config-data
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                echo "Config data received: $CONFIG_DATA"
                # Process config data in subsequent steps

  # Image file upload
  - name: file-block-image
    public: true
    plan:
      - task: create-image
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                # Create a simple PNG using ImageMagick or download a test image
                # For this example, we'll create a simple colored square
                apk add --no-cache imagemagick >/dev/null 2>&1 || true
                if command -v convert >/dev/null 2>&1; then
                  convert -size 200x200 xc:blue output/test-image.png
                else
                  # Fallback: download a test image
                  wget -q -O output/test-image.png https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif || true
                fi
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Image upload demonstration"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Image Upload Test"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Image uploaded using file block. Image files (PNG, JPG, JPEG, GIF) create image blocks automatically."
            - file:
                path: output/test-image.png
                title: "Test Image"
            - context:
                elements:
                  - type: plain_text
                    text: "Image blocks created automatically for image files"

  # Mixed file types with other blocks
  - name: file-blocks-mixed-content
    public: true
    plan:
      - task: create-mixed-files
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                echo "Deployment Log" > output/deploy.log
                echo "Test Results" > output/test-results.txt
                # Create a simple text file that looks like an image name for demo
                echo "PNG" > output/demo.png.txt
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Deployment notification with files"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Deployment Complete"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Status:* Success\n*Environment:* Production\n*Duration:* 2m 34s"
            - divider: {}
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "*Attached Files:*"
            - file:
                path: output/deploy.log
                title: "Deployment Log"
            - file:
                path: output/test-results.txt
                title: "Test Results"
            - divider: {}
            - context:
                elements:
                  - type: plain_text
                    text: "Deployed by: CI/CD Pipeline"
                  - type: mrkdwn
                    text: "*Time:* $(date '+%Y-%m-%d %H:%M:%S UTC')"

  # File block without title
  - name: file-block-no-title
    public: true
    plan:
      - task: create-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                set +x
                set -eo pipefail
                mkdir -p output
                echo "Report content" > output/automated-report-2024.txt
          outputs:
            - name: output

      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Filename used as title when no title specified"
            - file:
                path: output/automated-report-2024.txt
