resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  - name: header-with-plain-text-only
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Testing header block with plain_text only"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "A Heartfelt Header"

  - name: header-with-block-id-and-maximum-text
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Testing header block with block_id and maximum length text (150 characters)"
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "This header demonstrates the maximum allowed length of exactly 150 characters for header text blocks in Slack Block Kit format which is the limit here"
                block_id: "header_with_block_id_001"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Header block with `block_id` allows you to identify and reference this block in interaction payloads."
