resource_types:
  - name: slack
    type: docker-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  - name: basic-header
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Build Report"

  - name: header-with-block-id
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Deployment Report"
                block_id: "deployment_header"

  - name: header-long-text
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "System Health Check"

  - name: header-with-sections
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Weekly Report"
            - section:
                type: text
                text:
                  type: plain_text
                  text: "Weekly report summary"

  - name: header-multiple-headers
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Performance"
            - header:
                text:
                  type: plain_text
                  text: "Security"
            - header:
                text:
                  type: plain_text
                  text: "Compliance"
