resource_types:
  - name: slack
    type: docker-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  - name: image-with-url-title-and-block-id
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Testing image block with image_url, title, and block_id"
          blocks:
            - image:
                title:
                  type: plain_text
                  text: "Please enjoy this photo of a kitten"
                block_id: "image4"
                image_url: "http://placekitten.com/500/500"
                alt_text: "An incredibly cute kitten."

  - name: image-with-slack-file-url
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Testing image block with slack_file using url"
          blocks:
            - image:
                title:
                  type: plain_text
                  text: "Please enjoy this photo of a kitten"
                block_id: "image4"
                slack_file:
                  url: "https://files.slack.com/files-pri/T0123456-F0123456/xyz.png"
                alt_text: "An incredibly cute kitten."

  - name: image-with-slack-file-id
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          text: "Testing image block with slack_file using id"
          blocks:
            - image:
                title:
                  type: plain_text
                  text: "Please enjoy this photo of a kitten"
                block_id: "image4"
                slack_file:
                  id: "F0123456"
                alt_text: "An incredibly cute kitten."
