resource_types:
  - name: slack
    type: docker-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: notification-testing

jobs:
  - name: basic-image
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "A test image placeholder"

  - name: image-with-title
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "Success indicator image"
                title:
                  type: plain_text
                  text: "Build Success"

  - name: image-with-block-id
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "Warning indicator image"
                block_id: "warning_image_123"

  - name: image-multiple-images
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Image Gallery"
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "First image in gallery"
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "Second image in gallery"
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "Third image in gallery"

  - name: image-with-other-blocks
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - header:
                text:
                  type: plain_text
                  text: "Build Status Report"
            - section:
                type: text
                text:
                  type: mrkdwn
                  text: "Build completed successfully. See the build artifacts below."
            - image:
                image_url: "https://sunflowersoftware.ca/wp-content/uploads/2023/05/cropped-sunflower.gif"
                alt_text: "Build artifacts visualization"
                title:
                  type: plain_text
                  text: "Build Artifacts"
            - context:
                elements:
                  - type: plain_text
                    text: "Generated at $(date)"
