resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: latest

resources:
  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: ((channel))

jobs:
  - name: markdown-build-notification
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - markdown:
                text: |
                  **Build Status Report**

                  Build *#1234* completed *successfully* in `2m 34s`

                  **Test Results:**
                  - Unit tests: 245 passed
                  - Integration tests: 18 passed
                  - E2E tests: 12 passed

                  **Deployment:**
                  - Environment: production
                  - Version: v1.2.3
                  - Commit: [abc123def](https://github.com/org/repo/commit/abc123def)

                  See [full build logs](https://ci.example.com/builds/1234) for details.
