resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: sunflowersoftware/send-to-slack
      tag: v0.1.3

resources:
  - name: slack-notification
    type: slack-notification
    source:
      slack_bot_user_oauth_token: ((SLACK_BOT_USER_OAUTH_TOKEN))

common_slack_params: &common_slack_params
  channel: ((channel))

jobs:
  - name: table-basic-with-raw-text-cells
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - table:
                rows:
                  - - type: raw_text
                      text: "Project Name"
                    - type: raw_text
                      text: "Status"
                    - type: raw_text
                      text: "Completion Date"
                  - - type: raw_text
                      text: "Project Alpha"
                    - type: raw_text
                      text: "In Progress"
                    - type: raw_text
                      text: "2025-12-01"
                  - - type: raw_text
                      text: "Project Beta"
                    - type: raw_text
                      text: "Completed"
                    - type: raw_text
                      text: "2025-10-15"

  - name: table-with-all-features-column-settings-block-id-and-rich-text
    plan:
      - put: slack-notification
        no_get: true
        params:
          <<: *common_slack_params
          blocks:
            - table:
                block_id: "deployment_status_table"
                column_settings:
                  - align: left
                    is_wrapped: true
                  - align: center
                    is_wrapped: false
                  - align: right
                    is_wrapped: false
                rows:
                  - - type: raw_text
                      text: "Feature"
                    - type: raw_text
                      text: "Status"
                    - type: raw_text
                      text: "Documentation"
                  - - type: raw_text
                      text: "Text Wrapping"
                    - type: raw_text
                      text: "Enabled"
                    - type: rich_text
                      elements:
                        - type: rich_text_section
                          elements:
                            - type: link
                              url: "https://api.slack.com/block-kit"
                              text: "Block Kit Docs"
                  - - type: raw_text
                      text: "Column Alignment"
                    - type: raw_text
                      text: "Center"
                    - type: rich_text
                      elements:
                        - type: rich_text_section
                          elements:
                            - type: text
                              text: "Right aligned "
                            - type: link
                              url: "https://slack.com"
                              text: "link"
                  - - type: raw_text
                      text: "Rich Text Formatting"
                    - type: rich_text
                      elements:
                        - type: rich_text_section
                          elements:
                            - type: text
                              text: "Bold"
                              style:
                                bold: true
                            - type: text
                              text: " and "
                            - type: text
                              text: "italic"
                              style:
                                italic: true
                    - type: rich_text
                      elements:
                        - type: rich_text_section
                          elements:
                            - type: text
                              text: "Visit "
                            - type: link
                              url: "https://api.slack.com/messaging/composing/layouts"
                              text: "Layout Guide"
