name: run-bats-tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache yq
        uses: actions/cache@v4
        id: cache-yq
        with:
          path: /usr/local/bin/yq
          key: yq-v4.45.1-linux-amd64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq
          if [[ "${{ steps.cache-yq.outputs.cache-hit }}" != "true" ]]; then
            wget -qO /usr/local/bin/yq \
              https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64
            chmod +x /usr/local/bin/yq
          fi

      - name: Run shell tests
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: ./ci/run-bats.sh
